# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Vedant Pulahru"
resume_title:                   "Student"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "pulahru.vedant9@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "204-887-6556"
display_contact_telephone:      "false"
resume_contact_address:         "1833 Pembina highway"
display_contact_address:        "false"
resume_header_contact_info:     "1833 Pembina highway • 204-887-6556 • pulahru.vedant9@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>
Hi my name is Vedant Pulahru and I am a 4th-year student studying computer science at the University of Manitoba. 
I have successfully completed most of my major courses. I have been using my spare time to build my projects in java and python.
</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Vedant1206"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/vedant-pulahru-a196901b4/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

header_pages:  readme_portfolio.md

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
